# Demo 3 - Pandas Deeper Dive

This is a place for you to follow along live!

Use Shift+Enter to run a cell!

In [1]:
#Start typing code below!
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [4]:
filename = "./DemoCSV1.csv"
df = pd.read_csv(filename)

In [5]:
display(df)

Unnamed: 0                       Name  Miles_per_Gallon  Cylinders  \
0             0  chevrolet chevelle malibu              18.0          8   
1             1          buick skylark 320              15.0          8   
2             2         plymouth satellite              18.0          8   
3             3              amc rebel sst              16.0          8   
4             4                ford torino              17.0          8   
..          ...                        ...               ...        ...   
401         401            ford mustang gl              27.0          4   
402         402                  vw pickup              44.0          4   
403         403              dodge rampage              32.0          4   
404         404                ford ranger              28.0          4   
405         405                 chevy s-10              31.0          4   

     Displacement  Horsepower  Weight_in_lbs  Acceleration        Year  Origin  
0           307.0       130.0           3504          12.0  1970-01-01     USA  
1           350.0       165.0           3693          11.5  1970-01-01     USA  
2           318.0       150.0           3436          11.0  1970-01-01     USA  
3           304.0       150.0           3433          12.0  1970-01-01     USA  
4           302.0       140.0           3449          10.5  1970-01-01     USA  
..            ...         ...            ...           ...         ...     ...  
401         140.0        86.0           2790          15.6  1982-01-01     USA  
402          97.0        52.0           2130          24.6  1982-01-01  Europe  
403         135.0        84.0           2295          11.6  1982-01-01     USA  
404         120.0        79.0           2625          18.6  1982-01-01     USA  
405         119.0        82.0           2720          19.4  1982-01-01     USA  

[406 rows x 10 columns]

In [6]:
df.head()

Unnamed: 0                       Name  Miles_per_Gallon  Cylinders  \
0           0  chevrolet chevelle malibu              18.0          8   
1           1          buick skylark 320              15.0          8   
2           2         plymouth satellite              18.0          8   
3           3              amc rebel sst              16.0          8   
4           4                ford torino              17.0          8   

   Displacement  Horsepower  Weight_in_lbs  Acceleration        Year Origin  
0         307.0       130.0           3504          12.0  1970-01-01    USA  
1         350.0       165.0           3693          11.5  1970-01-01    USA  
2         318.0       150.0           3436          11.0  1970-01-01    USA  
3         304.0       150.0           3433          12.0  1970-01-01    USA  
4         302.0       140.0           3449          10.5  1970-01-01    USA

In [10]:
df.tail(10)

Unnamed: 0                        Name  Miles_per_Gallon  Cylinders  \
396         396  chrysler lebaron medallion              26.0          4   
397         397              ford granada l              22.0          6   
398         398            toyota celica gt              32.0          4   
399         399           dodge charger 2.2              36.0          4   
400         400            chevrolet camaro              27.0          4   
401         401             ford mustang gl              27.0          4   
402         402                   vw pickup              44.0          4   
403         403               dodge rampage              32.0          4   
404         404                 ford ranger              28.0          4   
405         405                  chevy s-10              31.0          4   

     Displacement  Horsepower  Weight_in_lbs  Acceleration        Year  Origin  
396         156.0        92.0           2585          14.5  1982-01-01     USA  
397         232.0       112.0           2835          14.7  1982-01-01     USA  
398         144.0        96.0           2665          13.9  1982-01-01   Japan  
399         135.0        84.0           2370          13.0  1982-01-01     USA  
400         151.0        90.0           2950          17.3  1982-01-01     USA  
401         140.0        86.0           2790          15.6  1982-01-01     USA  
402          97.0        52.0           2130          24.6  1982-01-01  Europe  
403         135.0        84.0           2295          11.6  1982-01-01     USA  
404         120.0        79.0           2625          18.6  1982-01-01     USA  
405         119.0        82.0           2720          19.4  1982-01-01     USA

In [11]:
# row, col
df.shape

(406, 10)

In [13]:
A = np.array([[1, 2, 3], [-1, -2, -3], [6, 5, -5]])
print(A)

[[ 1  2  3]
 [-1 -2 -3]
 [ 6  5 -5]]


In [14]:
df_A = pd.DataFrame(A)
print(df_A)

   0  1  2
0  1  2  3
1 -1 -2 -3
2  6  5 -5


In [15]:
column_names = ['Col A', 'Col B', 'Col C']
row_names = ['Happy', 'Halloween', 'Everyone!']

df_A.columns = column_names
df_A.index = row_names

display(df_A)

Col A  Col B  Col C
Happy          1      2      3
Halloween     -1     -2     -3
Everyone!      6      5     -5

In [16]:
print(df_A.loc['Everyone!', 'Col A'])

6


In [17]:
display(df_A.loc[:, 'Col B'])

Happy        2
Halloween   -2
Everyone!    5
Name: Col B, dtype: int64

In [19]:
display(df_A.loc['Halloween', :])

Col A   -1
Col B   -2
Col C   -3
Name: Halloween, dtype: int64

In [21]:
arr = df_A.loc['Halloween':, 'Col B' : 'Col C'].values
print(arr)

[[-2 -3]
 [ 5 -5]]


In [23]:
df_A.loc['Everyone!', 'Col B'] = 12
display(df_A)

Col A  Col B  Col C
Happy          1      2      3
Halloween     -1     -2     -3
Everyone!      6     12     -5

In [24]:
filename = './DemoCSV2.csv'
df = pd.read_csv(filename)
display(df)

Person          Place  Number
0     Ash           Home     1.0
1   James  Grocery Store     7.0
2  Jessie          Class     NaN
3   Brock            Lab    15.0
4   Misty            NaN    13.0
5    Dawn  Swimming Pool     NaN

In [26]:
# 0 - xaxis for rows
# 1 - yaxis for col
row_drop = df.dropna(axis=0)
display(row_drop)

Person          Place  Number
0    Ash           Home     1.0
1  James  Grocery Store     7.0
3  Brock            Lab    15.0

In [27]:
B= np.matrix('-1, 2; 3, 4')
B

matrix([[-1,  2],
        [ 3,  4]])